import { Metadata } from "next";
import useToken from "@/hooks/use-token";
import SettingsForm from "@/app/(dashboard)/components/root/SettingsForm";

export const metadata: Metadata = {
  title: "Dashboard | Account Settings",
  description: "Generated by create next nexus app",
};

const page = () => {
  const Token = useToken();
  const { sessionToken } = Token as { sessionToken: string };
  return <SettingsForm sessionToken={sessionToken as string} />;
};

export default page;
